language: node_js
node_js: stable

cache:
  directories:
    - "node_modules"

branches:
  only:
  - master

script:
  - npm run build:travis

before_install:
  - ./qshell account $AK $SK
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH=$HOME/.yarn/bin:$PATH
env:
  global:
    - GH_REF: git@github.com:LBJ0712/UI.git
    - GH_TOKEN:e21b24165c39558cbe24bd805a07055afd8761e9
    - P_BRANCH:gh-pages
    - U_EMILE:1728698030@qq.com
    - U_NAME:LBJ0712
after_success:
  - ./qshell qupload qiniu-config
  - ./qshell cdnrefresh -dirs cdnrefresh-dirs.txt
