language: node_js
# nodejs版本
node_js: 
   stable

# Travis-CI Caching
cache:
  directories:
    - node_modules


# S: Build Lifecycle
install:
  - npm install

before_script:

# 无其他依赖项所以执行npm run build 构建就行了
script:
  - npm run build:travis

after_script:
  - tar cf dist.tar ./dist
  - wget https://github.com/timvisee/ffsend/releases/download/v0.2.55/ffsend-v0.2.55-linux-x64-static
  - mv ./ffsend-* ./ffsend
  - chmod a+x ./ffsend
  - ./ffsend upload dist.tar
# E: Build LifeCycle

#指定分支，只有指定的分支提交时才会运行脚本
branches:
  only:
    - master
env:
 global:
   # 我将其添加到了travis-ci的环境变量中
   #- GH_REF: github.com/yimogit/metools.git 
after_success:
  - ./qshell qupload qiniu-config
  - ./qshell cdnrefresh -dirs cdnrefresh-dirs.txt
